language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - master
matrix:
  allow_failures:
    - php: master
install:
  # Composer
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer install
script:
  # Check code style
  - php vendor/bin/phpcs ./application --standard=PSR1,PSR2 --encoding=utf-8
notifications:
  email: false
